# Generated by Django 4.1.4 on 2022-12-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningboard',
            name='name',
            field=models.CharField(default='Learning Board Name', max_length=300),
        ),
        migrations.AlterField(
            model_name='learningboard',
            name='short_description',
            field=models.TextField(blank=True, default='Learning Board Description', max_length=300, verbose_name='Learning Board Description'),
        ),
        migrations.AlterField(
            model_name='learningboardcard',
            name='name',
            field=models.CharField(default='Learning Board Card Name', max_length=300),
        ),
        migrations.AlterField(
            model_name='learningboardcard',
            name='short_description',
            field=models.TextField(blank=True, default='Learning Board Card Description', max_length=300, verbose_name='Card Description'),
        ),
        migrations.AlterField(
            model_name='learningboardcardlist',
            name='name',
            field=models.CharField(default='Card List Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='learningboardcardlist',
            name='short_description',
            field=models.TextField(blank=True, default='Card List Description', max_length=300, verbose_name='Card List Description'),
        ),
        migrations.AlterField(
            model_name='learningboardcardlistitem',
            name='name',
            field=models.CharField(default='Learning Board Card List Item', max_length=50),
        ),
        migrations.AlterField(
            model_name='learningboardcardtag',
            name='name',
            field=models.CharField(default='Tag Name', max_length=50),
        ),
    ]
