# Generated by Django 4.1.4 on 2023-03-05 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='insight_literacy_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_non_verbal_memory_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_numeracy_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_verbal_memory_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_visual_perception_level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='literacy_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='non_verbal_memory_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numeracy_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verbal_memory_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visual_perception_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='executive_function_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verbal_reasoning_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visual_information_processing_speed_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
