# Generated by Django 4.1.4 on 2022-12-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_information',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='User Information'),
        ),
    ]
