# Generated by Django 4.1.4 on 2023-04-12 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHCP_Aspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_aspirations', models.TextField(blank=True, default="Student's Aspirations from EHCP'", max_length=300, verbose_name='EHCP Aspirations')),
            ],
        ),
        migrations.CreateModel(
            name='EHCP_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_interests', models.TextField(blank=True, default="Student's Interests from EHCP'", max_length=300, verbose_name='EHCP Interests')),
            ],
        ),
        migrations.CreateModel(
            name='EHCP_TeacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', max_length=300, verbose_name='Teacher Comment')),
            ],
        ),
        migrations.CreateModel(
            name='EHCP_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_views', models.TextField(blank=True, default="Student's Views from EHCP'", max_length=300, verbose_name='EHCP Views')),
                ('teacher_comments', models.ManyToManyField(blank=True, related_name='ehcp_views', to='Main.ehcp_teachercomment')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_type', models.CharField(default='Looking to participate', max_length=250)),
                ('time_chosen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='learningsubtask',
            name='learning_task',
        ),
        migrations.RemoveField(
            model_name='learningtask',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='learningtask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='learningtask',
            name='intended_for',
        ),
        migrations.RemoveField(
            model_name='subjectlearningoutcome',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='learning_subtask',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_literacy_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_non_verbal_memory_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_numeracy_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_verbal_memory_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='insight_visual_perception_level',
        ),
        migrations.RemoveField(
            model_name='learningboardcard',
            name='tags',
        ),
        migrations.AddField(
            model_name='customuser',
            name='debate_contribution_target',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='desired_engagement_type',
            field=models.CharField(choices=[('Looking to participate', 'Looking to participate'), ('Looking for discussion or group work', 'Looking for discussion or group work'), ('Looking to only listen in class', 'Looking to only listen in class'), ('Looking to uniquely contribute in class', 'Looking to uniquely contribute in class'), ('Looking to enagage in physical or hands-on activities', 'Looking to enagage in physical or hands-on activities'), ('Looking for occasional breaks or opportunities for quiet time', 'Looking for occasional breaks or opportunities for quiet time')], default='Looking to participate', max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='literacy_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='non_verbal_memory_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='numeracy_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verbal_memory_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visual_perception_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vocabulary_sheet_group',
            field=models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='M', max_length=20),
        ),
        migrations.AddField(
            model_name='learningboard',
            name='board_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='executive_function_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verbal_reasoning_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visual_information_processing_speed_level',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.DeleteModel(
            name='LearningBoardCardTag',
        ),
        migrations.DeleteModel(
            name='LearningSubTask',
        ),
        migrations.DeleteModel(
            name='LearningTask',
        ),
        migrations.DeleteModel(
            name='SubjectLearningOutcome',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.AddField(
            model_name='engagementinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ehcp_view',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ehcp_teachercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ehcp_interest',
            name='teacher_comments',
            field=models.ManyToManyField(blank=True, related_name='ehcp_interests', to='Main.ehcp_teachercomment'),
        ),
        migrations.AddField(
            model_name='ehcp_interest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ehcp_aspiration',
            name='teacher_comments',
            field=models.ManyToManyField(blank=True, related_name='ehcp_aspirations', to='Main.ehcp_teachercomment'),
        ),
        migrations.AddField(
            model_name='ehcp_aspiration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
