# Generated by Django 4.1.4 on 2022-12-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcategory',
            name='description',
        ),
    ]
