# Generated by Django 4.1.4 on 2023-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_ehcp_aspiration_ehcp_interest_ehcp_teachercomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ehcp_aspiration',
            options={'verbose_name_plural': 'EHCP Aspirations'},
        ),
        migrations.AlterModelOptions(
            name='ehcp_interest',
            options={'verbose_name_plural': 'EHCP Interests'},
        ),
        migrations.AlterModelOptions(
            name='ehcp_teachercomment',
            options={'verbose_name_plural': 'EHCP Teacher Comments'},
        ),
        migrations.AlterModelOptions(
            name='ehcp_view',
            options={'verbose_name_plural': 'EHCP Views'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='hasEHCP',
            field=models.BooleanField(default=False),
        ),
    ]
