# Generated by Django 4.1.4 on 2022-12-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_subjectcategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'verbose_name_plural': 'Subject Categories (Departments)'},
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_leader_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
