# Generated by Django 4.1.4 on 2023-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_customuser_insight_literacy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debate_contribution_target',
            field=models.FloatField(default=5),
        ),
    ]
