# Generated by Django 4.1.4 on 2023-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_customuser_debate_contribution_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vocabulary_sheet_group',
            field=models.CharField(choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='M', max_length=2),
        ),
    ]
