# Generated by Django 4.1.4 on 2023-04-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_ehcp_aspiration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehcp_aspiration',
            name='student_aspirations',
            field=models.TextField(blank=True, default="Student's Aspirations from EHCP - not setup yet", max_length=300, verbose_name='EHCP Aspirations'),
        ),
        migrations.AlterField(
            model_name='ehcp_interest',
            name='student_interests',
            field=models.TextField(blank=True, default="Student's Interests from EHCP - not setup yet", max_length=300, verbose_name='EHCP Interests'),
        ),
        migrations.AlterField(
            model_name='ehcp_view',
            name='student_views',
            field=models.TextField(blank=True, default="Student's Views from EHCP - not setup yet", max_length=300, verbose_name='EHCP Views'),
        ),
    ]
