# Generated by Django 4.1.4 on 2022-12-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_subjectcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year_group',
            field=models.CharField(choices=[('Year 7', 'Year 7'), ('Year 8', 'Year 8'), ('Year 9', 'Year 9'), ('Year 10', 'Year 10'), ('Year 11', 'Year 11')], default='Year_11', max_length=50),
        ),
    ]
