# Generated by Django 4.1.4 on 2022-12-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcategory',
            name='name',
            field=models.CharField(choices=[('Modern Foreign Languages', 'Modern Foreign Languages'), ('Humanity', 'Humanity'), ('Arts', 'Arts'), ('Technical', 'Technical'), ('Core', 'Core')], max_length=255),
        ),
    ]
