# Generated by Django 4.1.4 on 2022-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_channel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationarea',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
