# Generated by Django 4.1.4 on 2023-04-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_ehcp_teachercomment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebatingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('related_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.subject')),
            ],
        ),
    ]
