# Generated by Django 4.1.4 on 2023-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_learningboard_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='desired_engagement_type',
            field=models.CharField(choices=[('Looking to participate', 'Looking to participate'), ('Looking for discussion or group work', 'Looking for discussion or group work'), ('Looking to only listen in class', 'Looking to only listen in class'), ('Looking to uniquely contribute in class', 'Looking to uniquely contribute in class'), ('Looking to enagage in physical or hands-on activities', 'Looking to enagage in physical or hands-on activities'), ('Looking for occasional breaks or opportunities for quiet time', 'Looking for occasional breaks or opportunities for quiet time')], default='Looking to participate', max_length=250),
        ),
    ]
