# Generated by Django 4.1.4 on 2022-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_communicationarea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationarea',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
