# Generated by Django 4.1.4 on 2022-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_subject_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, default='', max_length=300, verbose_name='Learning Board Description')),
            ],
        ),
    ]
