# Generated by Django 4.1.4 on 2023-04-14 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_debatingarea_debate_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_name', models.CharField(max_length=255)),
                ('debating_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='Main.debatingarea')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('thumbs_up', models.PositiveIntegerField(default=0)),
                ('thumbs_down', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('debate_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='Main.debateside')),
            ],
        ),
        migrations.CreateModel(
            name='DebatingContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_contributed', models.FloatField(default=0)),
                ('debating_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.debatingarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
