# Generated by Django 4.1.4 on 2023-04-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_customuser_desired_engagement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtask',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='learningtask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='learningtask',
            name='intended_for',
        ),
        migrations.RemoveField(
            model_name='subjectlearningoutcome',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='learning_subtask',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='LearningSubTask',
        ),
        migrations.DeleteModel(
            name='LearningTask',
        ),
        migrations.DeleteModel(
            name='SubjectLearningOutcome',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
