# Generated by Django 4.1.4 on 2022-12-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_learningboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningBoardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, default='', max_length=300, verbose_name='Card Description')),
                ('learning_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.learningboard')),
            ],
        ),
        migrations.CreateModel(
            name='LearningBoardCardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, default='', max_length=300, verbose_name='Card Description')),
            ],
        ),
        migrations.CreateModel(
            name='LearningBoardCardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LearningBoardCardListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('learning_board_card_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.learningboardcardlist')),
            ],
        ),
        migrations.AddField(
            model_name='learningboardcardlist',
            name='items',
            field=models.ManyToManyField(related_name='items', to='Main.learningboardcardlistitem'),
        ),
        migrations.AddField(
            model_name='learningboardcardlist',
            name='learning_board_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.learningboardcard'),
        ),
        migrations.AddField(
            model_name='learningboardcard',
            name='lists',
            field=models.ManyToManyField(related_name='lists', to='Main.learningboardcardlist'),
        ),
        migrations.AddField(
            model_name='learningboardcard',
            name='tags',
            field=models.ManyToManyField(related_name='cards', to='Main.learningboardcardtag'),
        ),
        migrations.AddField(
            model_name='learningboard',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='Main.learningboardcard'),
        ),
    ]
