# Generated by Django 4.1.4 on 2023-04-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_learningtask_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_type', models.CharField(default='Looking to participate', max_length=250)),
                ('time_chosen', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
