# Generated by Django 4.1.4 on 2023-04-14 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_debateside_opinion_debatingcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='averageCD',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
