# Generated by Django 4.1.4 on 2023-04-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_engagementinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningboardcard',
            name='tags',
        ),
        migrations.DeleteModel(
            name='LearningBoardCardTag',
        ),
    ]
