# Generated by Django 4.1.4 on 2023-04-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_opinion_thumbs_down_remove_opinion_thumbs_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hasEHCP',
            field=models.BooleanField(default=True),
        ),
    ]
