# Generated by Django 4.1.4 on 2023-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_customuser_hasehcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.TextField(default='No text was given.'),
        ),
    ]
