# Generated by Django 4.1.4 on 2022-12-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_learningboard_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningboardcard',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='lists', to='Main.learningboardcardlist'),
        ),
        migrations.AlterField(
            model_name='learningboardcard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='Main.learningboardcardtag'),
        ),
    ]
