# Generated by Django 4.1.4 on 2023-04-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_ehcp_aspirations_ehcp_interests_ehcp_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHCP_Aspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_aspirations', models.TextField(blank=True, default="Student's Aspirations from EHCP'", max_length=300, verbose_name='EHCP Aspirations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EHCP_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_interests', models.TextField(blank=True, default="Student's Interests from EHCP'", max_length=300, verbose_name='EHCP Interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EHCP_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_views', models.TextField(blank=True, default="Student's Views from EHCP'", max_length=300, verbose_name='EHCP Views')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ehcp_interests',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ehcp_views',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ehcp_teachercomment',
            name='ehcp_aspirations',
        ),
        migrations.RemoveField(
            model_name='ehcp_teachercomment',
            name='ehcp_interests',
        ),
        migrations.RemoveField(
            model_name='ehcp_teachercomment',
            name='ehcp_views',
        ),
        migrations.RenameModel(
            old_name='Teacher_Comment',
            new_name='EHCP_TeacherComment',
        ),
        migrations.DeleteModel(
            name='EHCP_Aspirations',
        ),
        migrations.DeleteModel(
            name='EHCP_Interests',
        ),
        migrations.DeleteModel(
            name='EHCP_Views',
        ),
        migrations.AddField(
            model_name='ehcp_teachercomment',
            name='ehcp_aspiration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.ehcp_aspiration'),
        ),
        migrations.AddField(
            model_name='ehcp_teachercomment',
            name='ehcp_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.ehcp_interest'),
        ),
        migrations.AddField(
            model_name='ehcp_teachercomment',
            name='ehcp_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.ehcp_view'),
        ),
    ]
