# Generated by Django 4.1.4 on 2022-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_learningtask_userresponse_subjectlearningoutcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='learningtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
