# Generated by Django 4.1.4 on 2022-12-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_learningboardcard_lists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningboardcardlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='Main.learningboardcardlistitem'),
        ),
        migrations.AlterField(
            model_name='learningboardcardlist',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Card List Description'),
        ),
    ]
