# Generated by Django 4.1.4 on 2022-12-24 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_learningboardcardlist_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
