# Generated by Django 4.1.4 on 2023-02-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_remove_learningsubtask_learning_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtask',
            name='learning_outcomes',
        ),
    ]
