# Generated by Django 4.1.4 on 2023-05-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_opinion_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debatingcontribution',
            name='amount_contributed',
        ),
    ]
