# Generated by Django 4.1.4 on 2023-03-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_remove_learningtask_learning_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
