# Generated by Django 4.1.4 on 2023-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_debatingcontribution_amount_contributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningboardcard',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='card_attachments/'),
        ),
    ]
