# Generated by Django 4.1.4 on 2023-03-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_customuser_executive_function_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='insight_verbal_reasoning_level',
        ),
    ]
